### ISSUE TITLE
"adb is not installed!" even though it is

### ISSUE THREAD

**Issue by BacaR00T** [Kyuunex/better_droidcam_linux_client#3] opened 2023-08-12 20:47 UTC
``` 
bacar00t@archlinux ~/G/better_droidcam_linux_client (master) [127]> sudo ./droidcam
adb is not installed!
``` 
I use arch btw

**Comment by qnxt** [comment] 2023-08-12 20:49
try running without sudo

also what is the output of `which adb`?

**Comment by BacaR00T** [comment] 2023-08-12 21:05
Same as with sudo and 
```
bacar00t@archlinux ~> which adb
which: no adb in (/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

**Comment by qnxt** [comment] 2023-08-12 21:12
it seems like adb is not not found. which ADB did you install? if from arch repo, it should just work.

i looked it up and it seems like it's a part of [android-tools](https://archlinux.org/packages/extra/x86_64/android-tools/) package. 

Seems like I misdocumented this part, so I will correct that.

```
sudo pacman -S android-tools v4l2loopback-dkms ffmpeg android-udev --needed
```

If manually downloaded a package from somewhere and added it to your bashrc/PATH, then you require a reboot. i recommend trying the version from the arch repos.

**Comment by BacaR00T** [comment] 2023-08-12 21:18
After install and reboot I've got this:
```
bacar00t@archlinux ~/G/better_droidcam_linux_client (master) [SIGINT]> ./droidcam
waiting for the device to show up via adb
```
And it will just be waiting, have I'm not really sure if I have to edit something or what..

**Comment by qnxt** [comment] 2023-08-12 21:19
Connect your android device via USB, make sure to press allow on the device itself when it asks you

**Comment by BacaR00T** [comment] 2023-08-12 21:42
Okay so I've connected my Oppo Reno 5 to the computer and now it's asking me what I want to use USB for, options are:
File transfer/ Adnroid Auto, Photo transfer, USB tethering and MIDI. 
I've tried all of them and nothing

EDIT: my bad the USB debugging was disabled

**Comment by qnxt** [comment] 2023-08-12 21:45
okay, so what you need to do is to enable ADB (USB Debugging) in the developer settings. [droidcam website](https://www.dev47apps.com/droidcam/connect/) has instructions if you are having trouble.

**Comment by BacaR00T** [comment] 2023-08-12 21:50
Even after turning on the USB debugging I've got this:
```
bacar00t@archlinux ~/G/better_droidcam_linux_client (master) [1]> ./droidcam
waiting for the device to show up via adb
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/6.4.8-arch1-1
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mpjpeg, from 'http://127.0.0.1:4747/mjpegfeed?':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 640x480 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn
[video4linux2,v4l2 @ 0x55f23665fb80] Unable to open V4L2 device '/dev/video7'
[out#0/video4linux2,v4l2 @ 0x55f2366607c0] Could not write header (incorrect codec parameters ?): No such file or directory
[vost#0:0/copy @ 0x55f236661d00] Error initializing output stream: 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times

```
btw the IP cam works

**Comment by qnxt** [comment] 2023-08-12 21:53
try `sudo modprobe -r v4l2loopback`

this unloads v4l2loopback. then try running my script again.

the problem is, sometimes v4l2 breaks after you use it once (i assume you did it with IP cam.)

**Comment by BacaR00T** [comment] 2023-08-12 21:58
```
bacar00t@archlinux ~/G/better_droidcam_linux_client (master)> sudo modprobe -r v4l2loopback
modprobe: FATAL: Module v4l2loopback not found.
```
even though pacman is reporting it's up to date

**Comment by qnxt** [comment] 2023-08-12 22:00
you can try editing the source code and changing the number in DEVICE_NUMBER=7 to something else and trying again. other than that idk

**Comment by BacaR00T** [comment] 2023-08-12 22:07
Okay, can you give me a hint of what kind of range I should change the number? Like 0-99 or?
btw thanks so much for affort to help me <3

**Comment by qnxt** [comment] 2023-08-12 22:07
3-9

**Comment by BacaR00T** [comment] 2023-08-12 22:11
I'm gonna try

**Comment by ashish-kus** [comment] 2024-11-04 16:56
Is this issue still existing, or has it been resolved?

**Comment by qnxt** [comment] 2024-11-05 20:47
I'm just gonna close this and update the readme based on what this user had trouble with.

**Closed as completed by qnxt** 2024-11-05 20:47 UTC
